version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    assignees: [MishkaV]
    reviewers: [MishkaV]
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    assignees: [MishkaV]
    reviewers: [MishkaV]
    schedule:
      interval: weekly