changelog:
    categories:
        - title: 🐞 Bug Fixes
          labels:
              - bug
        - title: ✨ Features
          labels:
              - features
        - title: 🏗️ Infrastructure
          labels:
              - infrastructure
        - title: 🛠️ Tech Debt
          labels:
              - tech-debt
        -   title: 📚 Documentation
            labels:
                - documentation
        -   title: 👒 Dependencies
            labels:
                - dependencies
