name: Increment version
description: Increment patch version in gradle.properties and open a PR to main

inputs:
    release-version:
        description: 'The version that was just released (will be used for increment)'
        required: true

runs:
    using: composite
    steps:
        -   name: Calculate next version
            id: calculate_next_version
            shell: bash
            run: |
                RELEASE_VERSION="${{ inputs.release-version }}"

                # Remove -SNAPSHOT suffix if present (in case it was passed with suffix)
                CLEAN_VERSION="${RELEASE_VERSION%-SNAPSHOT}"

                # Split version into MAJOR.MINOR.PATCH
                IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN_VERSION"
                MAJOR=${MAJOR:-0}
                MINOR=${MINOR:-0}
                PATCH=${PATCH:-0}

                # Increment patch version
                NEXT_PATCH=$((PATCH + 1))
                NEXT_VERSION="$MAJOR.$MINOR.$NEXT_PATCH-SNAPSHOT"

                echo "Released version: $RELEASE_VERSION"
                echo "Next version: $NEXT_VERSION"
                echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

        -   name: Update version in gradle.properties
            shell: bash
            run: |
                bash ./scripts/update_version.sh "${{ steps.calculate_next_version.outputs.next_version }}"

        -   name: Configure git
            shell: bash
            run: |
                git config --local user.email "github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"

        -   name: Create branch, commit and push
            id: create_branch
            shell: bash
            run: |
                BRANCH_NAME="chore/bump-version-to-${{ steps.calculate_next_version.outputs.next_version }}"
                git checkout -b "$BRANCH_NAME"
                git add gradle.properties
                git commit -m "Update version to ${{ steps.calculate_next_version.outputs.next_version }}"
                git push origin "$BRANCH_NAME"
                echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

        -   name: Create Pull Request
            shell: bash
            env:
                GH_TOKEN: ${{ github.token }}
            run: |
                gh pr create \
                  --title "Update version to ${{ steps.calculate_next_version.outputs.next_version }}" \
                  --body "Automated version bump after release of \`${{ inputs.release-version }}\`." \
                  --base main \
                  --head "${{ steps.create_branch.outputs.branch_name }}"
