name: Check TODO in project

on:
  push:
    branches:
      - main

concurrency:
  group: check-todo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_todo:
    name: Check TODO in project
    uses: aiuta-com/aiuta-action/.github/workflows/check_todo.yaml@main
