name: Check new pull request

on:
  pull_request:
   types: [ opened ]

permissions:
  pull-requests: write

jobs:
  check_pr:
    uses: aiuta-com/aiuta-action/.github/workflows/check_pr.yaml@main
    with:
      prefix: "AIUTA-B2B"
    secrets:
      token: ${{ secrets.AIUTA_PERSONAL_ACCESS_TOKEN }}
