name: Check new pull request

on:
  pull_request:
  # TODO Return back
  # types: [ opened ]

permissions:
  pull-requests: write

jobs:
  check_pr:
    uses: aiuta-com/aiuta-action/.github/workflows/check_pr.yaml@main
    with:
      # TODO Make B2B
      prefix: "AIUTA-B2C"
    secrets:
      token: ${{ secrets.AIUTA_PERSONAL_ACCESS_TOKEN }}
