name: Check push to main branch

on:
  push:
    branches:
      - main

permissions:
    contents: write
    issues: write

concurrency:
  group: check-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_todo:
    name: Check TODO in project
    uses: aiuta-com/aiuta-action/.github/workflows/check_todo.yaml@main
