name: Build and deploy API docs

on:
    push:
        branches: [ main ]
        paths-ignore: [ 'README.md' ]
    release:
        types: [ published ]
    workflow_dispatch:

concurrency:
    group: release-api-docs-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Set release version
                id: set_release_version
                run: |
                    VERSION=$(git tag --sort=committerdate | tail -1)
                    bash ./scripts/update_version.sh $VERSION

            -   name: Generate API documentation
                run: ./scripts/make_docs.sh

            -   name: Setup Pages
                uses: actions/configure-pages@v4.0.0

            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v3.0.1
                with:
                    path: docs/api

            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4.0.4
