name: Publish to Maven central

on:
    release:
        types: [ published ]

concurrency:
    group: release-manual-maven-${{ github.ref }}
    cancel-in-progress: true

jobs:
    release_on_maven:
        name: Release on Maven Central
        runs-on: ubuntu-latest

        timeout-minutes: 180

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Base setup
                uses: ./.github/actions/setup-base

            -   name: Set release version
                id: set_release_version
                run: |
                    bash ./scripts/update_version.sh ${{ github.event.release.name }}

            -   name: Build and publish with Gradle
                uses: gradle/actions/setup-gradle@v3
                with:
                    arguments: --no-daemon -i jreleaserConfig build publish
                env:
                    JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
                    JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
                    JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME }}
                    JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN }}
                    JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}

            -   name: Release with gradle
                uses: gradle/actions/setup-gradle@v3
                with:
                    arguments: --no-daemon -i jreleaserFullRelease
                env:
                    JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
                    JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
                    JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME }}
                    JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN }}
                    JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
