name: CI
on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    # Limit concurrency to 1 for PRs
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    checks:
        name: Checks
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Base setup
                uses: ./.github/actions/setup-base

            -   name: Check style
                run: ./gradlew spotlessCheck

            -   name: Check lint
                run: ./gradlew lint

            -   name: Check binary compatibility
                run: ./gradlew apiCheck || { exit_code=$?; printf "*** This PR changes Aiuta's public API. If this change is intentional, run './gradlew apiDump' and commit the new API files. ***"; exit $exit_code; }

    build-samples:
        name: Build samples
        runs-on: macos-14
        timeout-minutes: 30
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Base setup
                uses: ./.github/actions/setup-base

            -   name: Build samples
                run: ./gradlew :samples:tryon:assembleDebug
